spring.application.name=skill-mentor-backend
server.port=${PORT:8081}

clerk.jwks.url=${CLERK_JWKS_URL}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Supabase Credentials
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=${SUPABASE_BUCKET}

# File Upload Configuration
file.upload.max-size=${FILE_UPLOAD_MAX_SIZE}
file.upload.allowed-types=${ALLOWED_FILE_TYPES}

spring.profiles.active=prod