spring.application.name=skill-mentor-backend
server.port=8081

clerk.jwks.url=https://model-bluebird-90.clerk.accounts.dev/.well-known/jwks.json

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.mymuiyiidkvxikbbrrpa&password=Supabase#3271
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#supabase.db.password=Supabase#3271

#Supabase Credentials
supabase.url=https://mymuiyiidkvxikbbrrpa.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15bXVpeWlpZGt2eGlrYmJycnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4OTEzNDEsImV4cCI6MjA4ODQ2NzM0MX0.KGophVjCnK3JImdwlXDAMwCxem7jVl6bcEMK7st9DzI
supabase.bucket=res

# File Upload Configuration
file.upload.max-size=5242880
file.upload.allowed-types=image/png,image/jpeg,image/jpg,image/gif,image/webp
